<?php
include_once("createSQL.php");
include_once("connectSQL.php");
include_once("createTables.php");
include_once("insertRegionLocation.php");
include_once("insertType.php");
include_once("insertAbility.php");
include_once("insertMove.php");
include_once("insertItem.php");
include_once("insertPokemon.php");
include_once("insertPokemon.php");
?>