<?php
include_once 'extractApi.php';

$sqlInsertAbility = 'INSERT INTO ability (id, name, description, smallDescription, effect) VALUES ';
$values = '';
echo getDataFromfile('/ability')->count;
echo '<br>';

foreach(getDataFromFile('/ability')->results as $ability)
{
    //echo $i;
    //echo '<br>';
    $abilityData = getDataFromFile('/ability/' . getIdFromUrl($ability->url));
    if ($abilityData->is_main_series == false) { break; }
    $value = '(' . $abilityData->id . ','; //id
    $value = $value . (getTextFromData($abilityData->names, 'name') == '"NULL///NULL"' ? '"' . getStringReplace($abilityData->name, false) . '///NULL"' : getTextFromData($abilityData->names, 'name')) . ','; //name
    $value = $value . getTextFromData($abilityData->effect_entries, 'effect') . ','; //description
    $value = $value . getTextFromData($abilityData->effect_entries, 'short_effect') . ','; //smallDescription
    $value = $value . getTextFromData($abilityData->flavor_text_entries, 'flavor_text'); //effect
    $value = $value . ')';
    $values = $values . $value . ',,';
    // if ($i == 20)
    // {
    //     break;
    // }
}
saveToDb($sqlInsertAbility, 'ability', $values);

$sqlAddBonusData = '';
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Les capacités physiques du Pokémon ont 10 % de chances d'apeurer la cible.") WHERE id=1`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Active le climat pluie lorsque le Pokémon est envoyé au combat.") WHERE id=2`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique de Vitesse du Pokémon augmente d'un niveau à chaque tour.") WHERE id=3`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Les coups critiques sont impossibles pour le Pokémon ennemi.") WHERE id=4`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre les capacités OHKO : le Pokémon résistera et gardera 1 PV s'il avait tous ses PV avant l'attaque.") WHERE id=5`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Le Pokémon adverse n'a pas la possibilité d'utiliser une capacité auto-destructrice.") WHERE id=6`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre le statut paralysie") WHERE id=7`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Sous le climat tempête de sable, l'Esquive du Pokémon augmente de 20 %.
Immunité contre les dégâts de la tempête de sable.") WHERE id=8`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Les capacités directes reçues ont 30 % de chances de donner le statut paralysie à leur lanceur.") WHERE id=9`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre les capacités de type Électrik : elles soignent jusqu'à 25 % des PV maximum du Pokémon.") WHERE id=10`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre les capacités de type Eau : elles soignent jusqu'à 25 % des PV maximum du Pokémon.") WHERE id=11`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre l'attraction, contre la provocation et contre l'intimidation.") WHERE id=12`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Annule les effets du climat.") WHERE id=13`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique de Précision du Pokémon augmente de 30 %.") WHERE id=14`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre le statut sommeil.") WHERE id=15`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Change le type du Pokémon en celui de la dernière capacité offensive subie.") WHERE id=16`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre le statut poison.") WHERE id=17`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre les capacités de type Feu : elles augmentent de 50 % la puissance des capacités de type Feu du Pokémon.") WHERE id=18`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Les effets secondaires des capacités ennemies sont annulés.") WHERE id=19`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre la confusion et contre l'intimidation.") WHERE id=20`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre le switch forcé.") WHERE id=21`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique d'Attaque du Pokémon adverse baisse lorsque le Pokémon est envoyé au combat.") WHERE id=22`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La fuite ou le switch d'un Pokémon adverse est impossible.") WHERE id=23`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Les capacités directes reçues font perdre 1/8 des PV maximum du lanceur.") WHERE id=24`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre les capacités offensives qui ne sont pas super efficaces, sauf Lutte.") WHERE id=25`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre les capacités de type Sol.
Immunité contre les champs.
Immunité contre Fertilisation, Picots, Pics Toxik, Piège Sable et Toile Gluante.") WHERE id=26`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Les capacités directes reçues ont 30 % de chances de donner le statut poison, paralysie ou sommeil à leur lanceur.") WHERE id=27`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Le Pokémon adverse obtient la brûlure, l'empoisonnement ou la paralysie subie par le Pokémon.") WHERE id=28`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre la diminution de statistiques du Pokémon imposée par un autre.") WHERE id=29`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Le Pokémon soigne ses altérations de statut s'il switch ou en fin de combat.") WHERE id=30`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre les capacités de type Électrik : elles augmentent d'un niveau l'Attaque Spéciale du Pokémon.
Les capacités de type Électrik utilisées par un Pokémon adjacent touchent obligatoirement ce Pokémon.") WHERE id=31`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Les effets secondaires des capacités du Pokémon ont leurs chances doublées.") WHERE id=32`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Sous le climat pluie, la Vitesse du Pokémon est doublée.") WHERE id=33`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Sous le climat soleil, la Vitesse du Pokémon est doublée.") WHERE id=34`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Ignorer les augmentations d'Esquive de sa cible, et de l'immuniser aux baisses de sa Précision.") WHERE id=35`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Change le talent du Pokémon en celui d'un Pokémon adverse.") WHERE id=36`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique d'Attaque du Pokémon est doublée.") WHERE id=37`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Les capacités directes reçues ont 30 % de chances de donner le statut poison à leur lanceur.") WHERE id=38`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre la peur et contre l'intimidation.") WHERE id=39`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre le statut gel.") WHERE id=40`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre le statut brûlure.") WHERE id=41`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La fuite ou le switch d'un Pokémon adverse de type Acier est impossible.") WHERE id=42`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre les capacités sonores.") WHERE id=43`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Sous le climat pluie, le Pokémon régénère 1/16 de ses PV maximum à chaque fin de tour.") WHERE id=44`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Active le climat tempête de sable lorsque le Pokémon est envoyé au combat.") WHERE id=45`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Le Pokémon adverse consomme deux fois plus de PP lorsqu'il utilise une capacité offensive.") WHERE id=46`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Diminue les dégâts subits par les capacités de type Feu et de type Glace.") WHERE id=47`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Le Pokémon se réveille deux fois plus rapidement.") WHERE id=48`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Les capacités directes reçues ont 30 % de chances de donner le statut brûlure à leur lanceur.") WHERE id=49`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La fuite du Pokémon contre un Pokémon sauvage est garantie.") WHERE id=50`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre la diminution de la Précision du Pokémon.") WHERE id=51`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre la diminution de l'Attaque du Pokémon.") WHERE id=52`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Après un combat, le Pokémon a une chance de ramasser un objet.") WHERE id=53`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Le Pokémon n'a pas la possibilité d'attaquer un tour sur deux.") WHERE id=54`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique d'Attaque du Pokémon augmente de 50 %.
Les capacités physiques du Pokémon ont leur Précision diminuée de 20 %.") WHERE id=55`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Les capacités directes reçues ont 30 % de chances de donner le statut attraction à leur lanceur de sexe opposé.") WHERE id=56`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique d'Attaque Spéciale du Pokémon augmente de 50 % si un allié en Combat Duo a le talent Plus ou Moins.") WHERE id=57`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique d'Attaque Spéciale du Pokémon augmente de 50 % si un allié en Combat Duo a le talent Plus ou Moins.") WHERE id=58`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Change la forme de Morphéo selon le climat.") WHERE id=59`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"L'objet tenu ne peut pas être perdu.") WHERE id=60`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Le Pokémon soigne ses altérations de statut à chaque tour. (1 chance sur 3)") WHERE id=61`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Avec un statut altéré, l'Attaque du Pokémon augmente de 50 %.
Immunité contre la diminution de l'Attaque du Pokémon imposée par le statut brûlure.") WHERE id=62`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Avec un statut altéré, la Défense du Pokémon augmente de 50 %.") WHERE id=63`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Inflige des dégâts au lieu de redonner des PV lorsque le Pokémon adverse utilise une capacité drainant des PV.") WHERE id=64`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Augmente la puissance des capacités de type Plante lorsque le Pokémon a moins d'1/3 de ses PV.") WHERE id=65`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Augmente la puissance des capacités de type Feu lorsque le Pokémon a moins d'1/3 de ses PV.") WHERE id=66`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Augmente la puissance des capacités de type Eau lorsque le Pokémon a moins d'1/3 de ses PV.") WHERE id=67`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Augmente la puissance des capacités de type Insecte lorsque le Pokémon a moins d'1/3 de ses PV.") WHERE id=68`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre le contrecoup.") WHERE id=69`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Active le climat soleil lorsque le Pokémon est envoyé au combat.") WHERE id=70`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La fuite ou le switch d'un Pokémon adverse ne volant pas est impossible.") WHERE id=71`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre le statut sommeil.") WHERE id=72`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre la diminution de statistiques du Pokémon imposée par un autre.") WHERE id=73`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique d'Attaque du Pokémon est doublée.") WHERE id=74`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Les coups critiques sont impossibles pour le Pokémon ennemi.") WHERE id=75`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Annule les effets du climat.") WHERE id=76`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Avec un statut confus, l'Esquive du Pokémon augmente de 50 %.") WHERE id=77`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre les capacités de type Électrik : elles augmentent d'un niveau la Vitesse du Pokémon.") WHERE id=78`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Augmente la puissance des capacités si le Pokémon adverse est du même sexe, mais la diminue s'il est du sexe opposé.") WHERE id=79`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Avec un statut apeuré, la Vitesse du Pokémon augmente d'un niveau.") WHERE id=80`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Sous le climat grêle, l'Esquive du Pokémon augmente de 20 %.
Immunité contre les dégâts de la grêle.") WHERE id=81`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La Baie tenue peut être consommée lorsque les PV descendent en dessous de 50 % au lieu de 25 %.") WHERE id=82`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique d'Attaque du Pokémon augmente de six niveaux s'il est touché par un coup critique.") WHERE id=83`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique de Vitesse du Pokémon est doublée s'il n'a plus d'objet tenu.") WHERE id=84`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Diminue les dégâts subits par les capacités de type Feu et par les effets de brûlure.") WHERE id=85`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Les effets des modifications de statistiques du Pokémon sont doublés, qu'ils soient positifs ou négatifs.") WHERE id=86`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Sous le climat soleil, le Pokémon perd 1/8 de ses PV maximum à chaque fin de tour.
Sous le climat pluie, le Pokémon régénère 1/8 de ses PV maximum à chaque fin de tour.
Les capacités de type Feu infligent 25 % de dégâts supplémentaires au Pokémon.
Immunité contre les capacités de type Eau : elles soignent jusqu'à 25 % des PV maximum du Pokémon.") WHERE id=87`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Augmente soit l'Attaque, soit l'Attaque Spéciale en fonction de la statistique de défense la plus faible du Pokémon adverse.") WHERE id=88`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Augmente la puissance des capacités coups de poing.") WHERE id=89`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Avec un statut empoisonné ou gravement empoisonné, le Pokémon régénère 1/8 de ses PV maximum au lieu d'en perdre.") WHERE id=90`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Augmente la puissance des capacités STAB.") WHERE id=91`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Les capacités du Pokémon frappent toujours le nombre de coups maximum.") WHERE id=92`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Sous le climat pluie, soigne le Pokémon des altériations de statut passées et futures.") WHERE id=93`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Sous le climat soleil, l'Attaque Spéciale du Pokémon augmente de 50 % mais il perd 1/8 de ses PV maximum à chaque fin de tour.") WHERE id=94`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Avec un statut altéré, la Vitesse du Pokémon augmente de 50 %.
Immunité contre la diminution de la Vitesse du Pokémon imposée par le statut paralysie.") WHERE id=95`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Change le type des capacités du Pokémon et les considère comme étant de type Normal.") WHERE id=96`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Les coups critiques du Pokémon ont une puissance triplée.") WHERE id=97`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre toutes les capacités qui ne sont pas directes.") WHERE id=98`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Les capacités du Pokémon et de l'adversaire ne peuvent pas échouer.") WHERE id=99`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Le Pokémon n'a pas la possibilité d'attaquer en premier s'il n'a pas la priorité.") WHERE id=100`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Augmente la puissance des capacités infligeant. 60 dégâts ou moins.") WHERE id=101`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Sous le climat soleil, soigne le Pokémon des altériations de statut futures.") WHERE id=102`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"L'objet tenu ne peut pas être utilisé.") WHERE id=103`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Ignore les talents adverses ayant un effet sur les capacités du Pokémon.") WHERE id=104`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Les coups critiques du Pokémon ont une chance doublée.") WHERE id=105`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Les capacités directes reçues mettant K.O. le Pokémon font perdre 25 % des PV maximum du lanceur.") WHERE id=106`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Détecte si le Pokémon adverse possède des capacités efficaces sur le Pokémon, des capacités OHKO ou les capacités Explosion et Destruction.") WHERE id=107`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Détecte la capacité la plus puissante du Pokémon adverse.") WHERE id=108`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Ignore les améliorations de statistiques du Pokémon adverse, à l'exception de sa Vitesse.") WHERE id=109`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Augmente la puissance des capacités peu efficaces sur le Pokémon adverse.") WHERE id=110`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Diminue les dégâts subits par les capacités super efficaces.") WHERE id=111`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique d'Attaque et de Vitesse du Pokémon sont divisées par deux pendant 5 tours.") WHERE id=112`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Ignore les immunités du type Spectre du Pokémon adverse. Il devient donc possible de toucher un Pokémon de ce type avec des capacités de type Normal ou Combat.") WHERE id=113`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre les capacités de type Eau : elles augmentent d'un niveau l'Attaque Spéciale du Pokémon.
Les capacités de type Eau utilisées par un Pokémon adjacent touchent obligatoirement ce Pokémon.") WHERE id=114`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Sous le climat grêle, le Pokémon régénère 1/16 de ses PV maximum à chaque fin de tour.
Immunité contre les dégâts de la grêle.") WHERE id=115`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Diminue les dégâts subits par les capacités super efficaces.") WHERE id=116`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Active le climat grêle lorsque le Pokémon est envoyé au combat.") WHERE id=117`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Après un combat, le Pokémon a une chance de ramasser du Miel.") WHERE id=118`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Détecte l'objet tenu par le Pokémon adverse.") WHERE id=119`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Augmente la puissance des capacités à contrecoup, sauf Lutte.") WHERE id=120`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Change la forme d'Arceus selon la Plaque tenue.") WHERE id=121`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Sous le climat soleil, l'Attaque et la Défense Spéciale du Pokémon et de ses alliés augmentent de 50 %.
Change la forme de Ceriflor selon le climat.") WHERE id=122`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Inflige 1/8e de ses PV au Pokémon adverse s'il est endormi.") WHERE id=123`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Les capacités directes reçues font voler au Pokémon l'objet tenu du lanceur.") WHERE id=124`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Augmente la puissance des capacités pouvant avoir un effet secondaire, mais annule ce dernier.") WHERE id=125`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Les effets des changements de statistiques sont inversés.") WHERE id=126`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La Baie tenue par le Pokémon adverse ne peut pas être consommée tant que le Pokémon est sur le terrain.") WHERE id=127`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique d'Attaque du Pokémon augmente de deux niveaux s'il subit une diminution de statistiques par un adversaire.") WHERE id=128`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique d'Attaque et d'Attaque Spéciale du Pokémon sont divisées par deux s'il a moins de 50 % de ses PV.") WHERE id=129`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Les capacités du Pokémon adverse ont 30 % de chances de s'entraver.") WHERE id=130`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Le Pokémon soigne les altérations de statut d'un allié adjacent. (30 % de chance)") WHERE id=131`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Diminue les dégâts subits par les alliés.") WHERE id=132`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique de Défense du Pokémon diminue d'un niveau et sa Vitesse augmente de deux lorsqu'il est touché par une capacité physique.") WHERE id=133`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Le poids du Pokémon est doublé.") WHERE id=134`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Le poids du Pokémon est divisé par deux.") WHERE id=135`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Diminue les dégâts subits par les capacités offensives si le Pokémon a tous ses PV.") WHERE id=136`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique d'Attaque du Pokémon augmente de 50 % s'il est empoisonné.") WHERE id=137`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique d'Attaque Spéciale du Pokémon augmente de 50 % s'il est brûlé.") WHERE id=138`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La Baie consommée a 50 % de chances d'être récupérée à la fin du tour.") WHERE id=139`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre les capacités des alliés en Combat Duo ou Trio.") WHERE id=140`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Augmente aléatoirement une statistique du Pokémon de deux niveaux et en baisse une autre d'un niveau à chaque tour. La Précision et l'Esquive sont comprises.") WHERE id=141`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre les dégâts de la grêle et de la tempête de sable.
Immunité contre les capacités poudreuses et le talent Pose Spore.") WHERE id=142`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Les capacités directes envoyées ont 30 % de chances de donner le statut poison à leur cible.") WHERE id=143`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Le Pokémon soigne 1/3 de ses PV s'il switch.") WHERE id=144`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre la diminution de la Défense du Pokémon.") WHERE id=145`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Sous le climat tempête de sable, la Vitesse du Pokémon est doublée.
Immunité contre les dégâts de la tempête de sable.") WHERE id=146`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Les capacités de statut du Pokémon adverse ont une chance sur deux d'échouer.") WHERE id=147`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Augmente la puissance des capacités si le Pokémon frappe en dernier durant le tour.") WHERE id=148`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Change l'apparence du Pokémon en celle du dernier Pokémon de l'équipe lorsque le Pokémon est envoyé au combat.") WHERE id=149`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Transforme le Pokémon de façon à imiter le Pokémon adverse lors de son entrée au combat.") WHERE id=150`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Ignore les capacités de protection adverses, sauf Détection et Abri.") WHERE id=151`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Remplace le talent de l'adversaire attaquant par Momie lorsque le détenteur subit une attaque directe.") WHERE id=152`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique d'Attaque du Pokémon augmente d'un niveau s'il met un Pokémon K.O.") WHERE id=153`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique d'Attaque du Pokémon augmente d'un niveau s'il est touché par une capacité de type Ténèbres.") WHERE id=154`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique de Vitesse du Pokémon augmente d'un niveau s'il est touché par une capacité de type Insecte, Spectre ou Ténèbres.") WHERE id=155`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Les capacités de statut sont retournées contre le Pokémon adverse.") WHERE id=156`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre les capacités de type Plante : elles augmentent d'un niveau l'Attaque du Pokémon.") WHERE id=157`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La priorité des capacités de statut augmente d'un niveau.") WHERE id=158`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Sous le climat tempête de sable, la puissance des capacités de type Acier, Roche et Sol du Pokémon augmente de 30 %.
Immunité contre les dégâts de la tempête de sable.") WHERE id=159`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Les capacités directes reçues font perdre 1/8 des PV maximum du lanceur.") WHERE id=160`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Les capacités directes reçues font perdre 1/8 des PV maximum du lanceur.") WHERE id=161`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Les capacités directes reçues font perdre 1/8 des PV maximum du lanceur.") WHERE id=162`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Les capacités directes reçues font perdre 1/8 des PV maximum du lanceur.") WHERE id=163`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Les capacités directes reçues font perdre 1/8 des PV maximum du lanceur.") WHERE id=164`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre les attaques limitant le choix des capacités pour le Pokémon et ses alliés sur le terrain.") WHERE id=165`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre la diminution de statistiques du Pokémon et des alliés de type Plante imposée par un autre.") WHERE id=166`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La Baie tenue permet aussi de récupérer 1/3 de ses PV totaux.") WHERE id=167`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Change le type du Pokémon en celui de toute capacité qu'il utilise.") WHERE id=168`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique de Défense du Pokémon est doublée.") WHERE id=169`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"L'objet tenu par le Pokémon adverse est volé lorsque le Pokémon le touche avec une capacité directe.") WHERE id=170`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre les capacités à projectiles.") WHERE id=171`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique d'Attaque Spéciale du Pokémon augmente de deux niveaux s'il subit une diminution de statistiques par un adversaire.") WHERE id=172`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Augmente la puissance des capacités à base de morsures.") WHERE id=173`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Change le type des capacités de type Normal du Pokémon et les considère comme étant de type Glace. Augmente la puissance de ces capacités.") WHERE id=174`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre le statut sommeil pour le Pokémon et ses alliés.") WHERE id=175`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Change la forme d'Exagide selon les capacités qu'il utilise.") WHERE id=176`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La priorité des capacités de type Vol augmente d'un niveau.") WHERE id=177`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Augmente la puissance des capacités d'aura.") WHERE id=178`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Sous un Champ Herbu, la Défense du Pokémon augmente de 50 %.") WHERE id=179`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"L'objet tenu est donné à l'allié lorsque ce dernier utilise le sien.") WHERE id=180`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Les capacités directes utilisées par le Pokémon infligent 30 % de dégâts supplémentaires.") WHERE id=181`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Change le type des capacités de type Normal du Pokémon et les considère comme étant de type Fée. Augmente la puissance de ces capacités.") WHERE id=182`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Les capacités directes reçues font diminuer la Vitesse du lanceur.") WHERE id=183`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Change le type des capacités de type Normal du Pokémon et les considère comme étant de type Vol. Augmente la puissance de ces capacités.") WHERE id=184`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Les capacités du Pokémon frappe deux fois par tour au lieu d'un, mais le deuxième coup fait deux fois moins de dégâts que le premier.") WHERE id=185`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Augmente la puissance des capacités de type Ténèbres.") WHERE id=186`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Augmente la puissance des capacités de type Fée.") WHERE id=187`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Diminue la puissance des capacités de type Fée quand Aura Féérique est actif.
Diminue la puissance des capacités de type Ténèbres quand Aura Ténébreuse est actif.") WHERE id=188`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Active le climat pluie battante lorsque le Pokémon est envoyé au combat.") WHERE id=189`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Active le climat soleil intense lorsque le Pokémon est envoyé au combat.") WHERE id=190`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Active le climat vent mystérieux lorsque le Pokémon est envoyé au combat.") WHERE id=191`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique de Défense du Pokémon augmente d'un niveau s'il est touché par une capacité offensive.") WHERE id=192`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La fuite ou le switch du Pokémon est automatique s'il a moins de 50 % de ses PV.") WHERE id=193`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La fuite ou le switch du Pokémon est automatique s'il a moins de 50 % de ses PV.") WHERE id=194`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique de Défense du Pokémon augmente de deux niveaux s'il est touché par une capacité de type Eau.") WHERE id=195`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Les coups critiques sont systémiques contre un ennemi empoisonné.") WHERE id=196`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Change la forme de Météno lorsque ses PV descendent sous les 50 %.
Immunité aux capacités de statut lorsqu'il est sous sa forme Météore. Il perd cette immunité lorsqu'il change de forme.") WHERE id=197`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Augmente la puissance des capacités des Pokémon arrivant au milieu d'un combat.") WHERE id=198`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Diminue les dégâts subits par les capacités de type Feu.
Augmente la puissance des capacités de type Eau.
Immunité au statut brûlure.") WHERE id=199`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Augmente la puissance des capacités de type Acier.") WHERE id=200`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique d'Attaque Spéciale du Pokémon augmente d'un niveau s'il passe en dessous de 50 % de ses PV.") WHERE id=201`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Sous le climat grêle, la Vitesse du Pokémon est doublée.") WHERE id=202`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Les capacités du Pokémon sont toutes considérées comme étant sans contact.") WHERE id=203`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Les capacités sonores du Pokémon deviennent de type Eau.") WHERE id=204`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La priorité des capacités de soin augmente de trois niveaux.") WHERE id=205`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Change le type des capacités de type Normal du Pokémon et les considère comme étant de type Électrik. Augmente la puissance de ces capacités.") WHERE id=206`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Sous un Champ Électrifié, la Vitesse du Pokémon est doublée.") WHERE id=207`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Change la forme de Froussardine si ses PV sont supérieurs à 25 % du maximum.") WHERE id=208`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Change la forme de Mimiqui après les premiers dégâts encaissés.") WHERE id=209`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Change la forme d'Amphinobi après avoir vaincu un adversaire.") WHERE id=210`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Change la forme de Zygarde si ses PV sont inférieurs à 50 % du maximum.") WHERE id=211`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Ignore l'immunité à l'empoisonnement des types Acier et Poison.") WHERE id=212`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre les statuts, sauf le sommeil, car le Pokémon est endormi en tout temps. Il peut attaquer normalement malgré cela.") WHERE id=213`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Le Pokémon adverse n'a pas la possibilité d'utiliser une capacité de priorité.") WHERE id=214`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Inflige à l'adversaire des dégâts équivalents au nombre de PV qu'il restait au Pokémon avant d'être mis K.O.") WHERE id=215`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Permet d'utiliser les capacités de danse utilisées par les autres Pokémon.") WHERE id=216`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Augmente la puissance des capacités spéciales des alliés.") WHERE id=217`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Diminue les dégâts subits par les capacités directes qui ne sont pas de type Feu.
Augmente les dégâts subits par les capacités de type Feu.") WHERE id=218`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Le Pokémon adverse n'a pas la possibilité d'utiliser une capacité de priorité.") WHERE id=219`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique d'Attaque Spéciale du Pokémon augmente d'un niveau si un Pokémon est mis K.O.") WHERE id=220`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique de Vitesse de l'attaquant diminue lorsque le Pokémon subit une attaque directe.") WHERE id=221`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Change le talent du Pokémon en celui d'un allié mis K.O.") WHERE id=222`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Change le talent du Pokémon en celui d'un allié mis K.O.") WHERE id=223`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique la plus élevée du Pokémon augmente d'un niveau s'il met un Pokémon K.O.") WHERE id=224`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Change la forme de Silvallié selon la ROM tenue.") WHERE id=225`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Active un Champ Électrifié lorsque le Pokémon est envoyé au combat.") WHERE id=226`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Active un Champ Psychique lorsque le Pokémon est envoyé au combat.") WHERE id=227`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Active un Champ Brumeux lorsque le Pokémon est envoyé au combat.") WHERE id=228`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Active un Champ Herbu lorsque le Pokémon est envoyé au combat.") WHERE id=229`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre la diminution de statistiques du Pokémon imposée par un autre.") WHERE id=230`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Diminue les dégâts subits par les capacités offensives si le Pokémon a tous ses PV.") WHERE id=231`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Diminue les dégâts subits par les capacités super efficaces.") WHERE id=232`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Augmente la puissance des capacités super efficaces.") WHERE id=233`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique d'Attaque du Pokémon augmente d'un niveau en entrant sur le terrain.") WHERE id=234`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique de Défense du Pokémon augmente d'un niveau en entrant sur le terrain.") WHERE id=235`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Change le type du Pokémon en celui de toute capacité qu'il utilise.") WHERE id=236`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"L'objet Ball peut être récupéré si le Dresseur rate la capture d'un Pokémon sauvage et que le Pokémon ne tient pas d'objet. N'affecte que la première Ball perdue.") WHERE id=237`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique de Vitesse du Pokémon adverse diminue lorsque le Pokémon est touché par une capacité.") WHERE id=238`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Ignore les effets des capacités ou des talents attirant les capacités.") WHERE id=239`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Les effets réducteurs de statistiques sont renvoyés au Pokémon adverse.") WHERE id=240`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Change la forme de Nigosier lorsqu'il utilise la capacité Surf ou Plongée. S'il subit des dégâts par la suite, il recrache ce qu'il a dans le bec sur le Pokémon adverse.") WHERE id=241`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Ignore les effets des capacités ou des talents attirant les capacités.") WHERE id=242`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique de Vitesse du Pokémon augmente de six niveaux s'il est touché par une capacité de type Feu ou Eau.") WHERE id=243`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Augmente la puissance des capacités sonores. Le Pokémon ne subit que la moitié des dégâts quand il est touché par ce genre de capacités.") WHERE id=244`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Active le climat tempête de sable lorsque le Pokémon est touché par une capacité offensive.") WHERE id=245`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Diminue les dégâts subits par les capacités spéciales.") WHERE id=246`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La Baie tenue a un effet doublé.") WHERE id=247`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Change la forme de Bekaglaçon après les premiers dégâts physiques encaissés.
Rechange la forme de Bekaglaçon s'il grêle.") WHERE id=248`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Augmente la puissance des capacités des alliés du Pokémon se trouvant sur le terrain.") WHERE id=249`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Change le type du Pokémon en celui du champ actif.") WHERE id=250`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Annule les effets de Mur Lumière, Protection et Voile Aurore pour tous les Pokémon lorsque le Pokémon est envoyé au combat.") WHERE id=251`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Augmente la puissance des capacités de type Acier du Pokémon et de ses alliés.") WHERE id=252`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Force le Pokémon et l'adversaire à tomber K.O. trois tours après que le Pokémon a été touché par une capacité directe, à moins qu'ils ne soient remplacés entre temps.") WHERE id=253`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Remplace le talent du Pokémon adverse par Âme Vagabonde et prend possession de son ancien lorsque le Pokémon subit une capacité directe.") WHERE id=254`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique d'Attaque est augmentée, mais il devient impossible d'utiliser toute autre capacité que celle utilisée en premier par le Pokémon.") WHERE id=255`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Annule les effets des talents des autres Pokémon.") WHERE id=256`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre l'empoisonnement pour le Pokémon et ses alliés sur le terrain.") WHERE id=257`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Change la forme de Morpeko entre chaque tour.
Change le type de Roue Libre entre chaque tour.") WHERE id=258`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Les capacités du Pokémon ont 20 % de chances d'être prioritaires.") WHERE id=259`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Ignore les effets d'Abri et de ses équivalents (sauf Gardomax) si la capacité utilisée est physique.") WHERE id=260`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Annule tous les changements de statistiques des alliés lorsque le Pokémon est envoyé au combat.") WHERE id=261`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Augmente la puissance des capacités de type Électrik.") WHERE id=262`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Augmente la puissance des capacités de type Dragon.") WHERE id=263`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique d'Attaque du Pokémon augmente d'un niveau s'il met un Pokémon K.O.") WHERE id=264`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique d'Attaque Spéciale du Pokémon augmente d'un niveau s'il met un Pokémon K.O.") WHERE id=265`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Combine les talents Tension et Blanche Ruade.") WHERE id=266`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Combine les talents Tension et Sombre Ruade.") WHERE id=267`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre les capacités de type Sol : elles soignent jusqu'à 25 % des PV maximum du Pokémon.") WHERE id=268`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique d'Attaque du Pokémon augmente si un vent arrière souffle ou s'il est touché par une capacité faisant appel au vent. Dans ce dernier cas, il ne subit aucun dégât.") WHERE id=269`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre les capacités prioritaires.") WHERE id=270`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre les capacités de type Feu : elles augmentent beaucoup la Défense du Pokémon.") WHERE id=271`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique d'Attaque de tous les autres Pokémon diminue lorsque le Pokémon est envoyé au combat.") WHERE id=272`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique la plus élevée du Pokémon augmente quand un Champ Électrifié est actif ou qu'une capsule d'Énergie Booster est tenue.") WHERE id=273`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre les capacités ou objets faisant changer de Pokémon.
Immunité contre le talent Intimidation : la statistique d'Attaque augmente au lieu de diminuer.") WHERE id=274`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Copie les changements de statistiques de l'allié lorsque le Pokémon est envoyé au combat.") WHERE id=275`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Augmente toutes les statistiques de deux niveaux d'un Oyacata allié se trouvant sur le terrain lorsque le Pokémon est envoyé au combat. Le Pokémon entre dans sa bouche.") WHERE id=276`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre les capacités de statut.") WHERE id=277`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique de Défense et de Défense Spéciale diminuent, mais la statistique d'Attaque, d'Attaque Spéciale et de Vitesse augmentent si le Pokémon a moins de la moitié de ses PV après avoir subi une attaque.") WHERE id=278`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Pose des pics toxiques dans le camp adverse lorsque le Pokémon est touché par une capacité physique.") WHERE id=279`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique de Défense de tous les autres Pokémon diminue lorsque le Pokémon est envoyé au combat.") WHERE id=280`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Ignore les talents adverses, mais le Pokémon agit toujours plus lentement quand il utilise une capacité de statut.") WHERE id=281`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique d'Attaque et d'Attaque Spéciale augmentent de 10 % pour chaque allié mis K.O. avant l'arrivée du Pokémon sur le terrain.") WHERE id=282`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Augmente la puissance de la prochaine capacité de type Électrik lorsque le Pokémon subit des dégâts.") WHERE id=283`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Augmente la puissance des capacités tranchantes.") WHERE id=284`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Active un Champ Électrifié lorsque le Pokémon est envoyé au combat.
La statistique d'Attaque Spéciale augmente si un Champ Électrifié est déjà actif.") WHERE id=285`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Remplace le talent de l'adversaire attaquant par Odeur Tenace lorsque le Pokémon subit une attaque directe.") WHERE id=286`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Augmente les statistiques du Pokémon de la même manière que le Pokémon adverse.") WHERE id=287`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique la plus élevée du Pokémon augmente quand le soleil brille ou qu'une capsule d'Énergie Booster est tenue.") WHERE id=288`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique de Défense Spéciale de tous les autres Pokémon diminue lorsque le Pokémon est envoyé au combat.") WHERE id=289`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Augmente la puissance des capacités de type Roche.") WHERE id=290`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Active le climat soleil lorsque le Pokémon est envoyé au combat.
La statistique d'Attaque augmente si le climat est déjà ensoleillé.") WHERE id=291`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La Baie tenue peut être consommée une deuxième fois à la fin du tour suivant.") WHERE id=292`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre les altérations de statut.
Diminue de moitié les dégâts des capacités de type Spectre.") WHERE id=293`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Active un Champ Herbu lorsque le Pokémon subit une attaque.") WHERE id=294`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Change la forme de Superdofin lorsqu'il est retiré du combat.") WHERE id=295`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Immunité contre les capacités de type Feu : elles augmentent l'Attaque du Pokémon.") WHERE id=296`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Augmente la puissance de la prochaine capacité de type Électrik lorsque le Pokémon est touché par une capacité faisant appel au vent.") WHERE id=297`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique d'Attaque Spéciale de tous les autres Pokémon diminue lorsque le Pokémon est envoyé au combat.") WHERE id=298`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Lorsqu'il entre en combat, le Pokémon restaure les PV d'un allié.") WHERE id=299`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Les capacités directes reçues ont 30 % de chances de donner le statut empoisonnement grave à leur lanceur.") WHERE id=300`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Une statistique augmente d'un cran lors de la téracristalisation selon le masque du Pokémon.") WHERE id=301`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"La statistique d'Esquive des Pokémon adverses diminue lorsque le Pokémon est envoyé au combat.") WHERE id=302`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Ignore les immunités du type Spectre et les changements d'Esquive du Pokémon adverse. Empêche aussi les diminutions de Précision du Pokémon.") WHERE id=303`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Change la forme de Terapagos en entrant sur le terrain.") WHERE id=304`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Les capacités offensives reçues par le Pokémon sont toujours peu efficaces s'il a 100 % de ses PV.") WHERE id=305`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Neutralise les effets des climats et champs actifs en entrant sur le terrain.") WHERE id=306`;
$sqlAddBonusData .= `UPDATE ability SET smallDescription=CONCAT(SUBSTRING(smallDescription, 1, POSITION('///NULL' IN smallDescription)+2),"Avec un statut empoisonné obtenu autrement que via des Pics Toxik, le Pokémon adverse devient confus.") WHERE id=307`;
saveToDb($sqlAddBonusData, '', '', false, true);

include_once 'readTxtUpdate.php';
addDataUpdate('TalentFR.txt', 'ability', 'smallDescription');
